#include "./TDetector.h"
#include "./TExogam2.h"
#include "./TExogam2Data.h"
#include "./TTrigger.h"
#include "./TTriggerData.h"
#include "./TExogamData.h"
#include "./TCsI.h"
#include "./TCsIData.h"
#include "./TNWall.h"
#include "./TNWallData.h"
#include "./TMW.h"
#include "./TMWData.h"
#include "./TParis.h"
#include "./TParisData.h"
#include "TString.h"
#include "TObjArray.h"
#include "TObjString.h"
#include <TGPicture.h>
#include <TGMenu.h>
#include <TGImageMap.h>
#include <TGMsgBox.h>
#include <iostream>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <cstring>
#include <unistd.h>
