// Numexo Topolgy for Lise 2022
// Name Board_Id, Type, Sample
// Date : 8/11/2021

****NUMEXOBoard****
Name      : S1_Sectors
Type      : IC
BoardNr   : 207
Channels  : 16
Samples   : -1
Active Channels : 16
Ch 00 : S1_S_00
Ch 01 : S1_S_01
Ch 02 : S1_S_02
Ch 03 : S1_S_03
Ch 04 : S1_S_04
Ch 05 : S1_S_05
Ch 06 : S1_S_06
Ch 07 : S1_S_07
Ch 08 : S1_S_08
Ch 09 : S1_S_09
Ch 10 : S1_S_10
Ch 11 : S1_S_11
Ch 12 : S1_S_12
Ch 13 : S1_S_13
Ch 14 : S1_S_14
Ch 15 : S1_S_15

//****NUMEXOBoard****
//Name      : IC
//Type      : IC
//BoardNr   : 207
//Channels  : 10
//Samples   : -1
//Active Channels : 10
//Ch 00 : IC_00
//Ch 01 : IC_01
//Ch 02 : IC_02
//Ch 03 : IC_03
//Ch 04 : IC_04
//Ch 05 : IC_05
//Ch 06 : IC_06
//Ch 07 : IC_07
//Ch 08 : IC_08
//Ch 09 : IC_09
////Ch 10 : IC_10
////Ch 11 : IC_11
////Ch 12 : IC_12
////Ch 13 : IC_13
////Ch 14 : IC_14
////Ch 15 : IC_15

****NUMEXOBoard****
Name      : S1_Strips
Type      : IC
BoardNr   : 212
Channels  : 16
Samples   : -1
Active Channels : 16
Ch 00 : S1_U_Str_00
Ch 01 : S1_U_Str_01
Ch 02 : S1_U_Str_02
Ch 03 : S1_U_Str_03
Ch 04 : S1_U_Str_04
Ch 05 : S1_U_Str_05
Ch 06 : S1_U_Str_06
Ch 07 : S1_U_Str_07
Ch 08 : S1_U_Str_08
Ch 09 : S1_U_Str_09
Ch 10 : S1_U_Str_10
Ch 11 : S1_U_Str_11
Ch 12 : S1_U_Str_12
Ch 13 : S1_U_Str_13
Ch 14 : S1_U_Str_14
Ch 15 : S1_U_Str_15


****NUMEXOBoard****
Name      : S1_Strips
Type      : IC
BoardNr   : 215
Channels  : 16
Samples   : -1
Active Channels : 16
Ch 00 : S1_U_Str_16
Ch 01 : S1_U_Str_17
Ch 02 : S1_U_Str_18
Ch 03 : S1_U_Str_19
Ch 04 : S1_U_Str_20
Ch 05 : S1_U_Str_21
Ch 06 : S1_U_Str_22
Ch 07 : S1_U_Str_23
Ch 08 : S1_U_Str_24
Ch 09 : S1_U_Str_25
Ch 10 : S1_U_Str_26
Ch 11 : S1_U_Str_27
Ch 12 : S1_U_Str_28
Ch 13 : S1_U_Str_29
Ch 14 : S1_U_Str_30
Ch 15 : S1_U_Str_31


****NUMEXOBoard****
Name      : S1_Strips
Type      : IC
BoardNr   : 216
Channels  : 16
Samples   : -1
Active Channels : 16
Ch 00 : S1_D_Str_00
Ch 01 : S1_D_Str_01
Ch 02 : S1_D_Str_02
Ch 03 : S1_D_Str_03
Ch 04 : S1_D_Str_04
Ch 05 : S1_D_Str_05
Ch 06 : S1_D_Str_06
Ch 07 : S1_D_Str_07
Ch 08 : S1_D_Str_08
Ch 09 : S1_D_Str_09
Ch 10 : S1_D_Str_10
Ch 11 : S1_D_Str_11
Ch 12 : S1_D_Str_12
Ch 13 : S1_D_Str_13
Ch 14 : S1_D_Str_14
Ch 15 : S1_D_Str_15


****NUMEXOBoard****
Name      : S1_Strips
Type      : IC
BoardNr   : 218
Channels  : 16
Samples   : -1
Active Channels : 16
Ch 00 : S1_D_Str_16
Ch 01 : S1_D_Str_17
Ch 02 : S1_D_Str_18
Ch 03 : S1_D_Str_19
Ch 04 : S1_D_Str_20
Ch 05 : S1_D_Str_21
Ch 06 : S1_D_Str_22
Ch 07 : S1_D_Str_23
Ch 08 : S1_D_Str_24
Ch 09 : S1_D_Str_25
Ch 10 : S1_D_Str_26
Ch 11 : S1_D_Str_27
Ch 12 : S1_D_Str_28
Ch 13 : S1_D_Str_29
Ch 14 : S1_D_Str_30
Ch 15 : S1_D_Str_31

****NUMEXOBoard****
Name      : TACS
Type      : TAC
BoardNr   : 108
Channels  : 16
Samples   : -1
Active Channels : 2
Ch 00 : T_00
Ch 01 : T_01
