#Put here a list of Gamma Gamma Matrices, you would like to have
#The PID must be specified and is Calculated by PID = 16*NProtons+4*NAlpha+Neutrons
#Each line is a new matrix, which will be produced
#PID
1
4
5
6
20
22

